/**
 * Project configuration
 * This file is auto-generated by pipecat-cli
 */

import type { DailyConnectionEndpoint } from '@pipecat-ai/daily-transport';

type SmallWebRTCConfig = {
  webrtcRequestParams: {
    endpoint: string;
  };
};

type TransportConfig = DailyConnectionEndpoint | SmallWebRTCConfig;

export type TransportType = 'daily' | 'smallwebrtc';

export const AVAILABLE_TRANSPORTS: TransportType[] = [
  'smallwebrtc',
  'daily',
];

export const DEFAULT_TRANSPORT: TransportType = 'smallwebrtc';

const botStartUrl =
  import.meta.env.VITE_BOT_START_URL || 'http://localhost:7860/start';
const botStartPublicApiKey = import.meta.env.VITE_BOT_START_PUBLIC_API_KEY;

if (!import.meta.env.VITE_BOT_START_URL) {
  console.warn(
    'VITE_BOT_START_URL not configured, using default: http://localhost:7860/start'
  );
}

const dailyConfig: DailyConnectionEndpoint = {
  endpoint: botStartUrl,
  requestData: {
    createDailyRoom: true,
    dailyRoomProperties: { start_video_off: true },
  },
};

if (botStartPublicApiKey) {
  dailyConfig.headers = new Headers({
    Authorization: `Bearer ${botStartPublicApiKey}`,
  });
}

export const TRANSPORT_CONFIG: Record<TransportType, TransportConfig> = {
  daily: dailyConfig,
  smallwebrtc: { webrtcRequestParams: { endpoint: 'http://localhost:7860/api/offer' } },
};
